### ISSUE TITLE
Duplicate and Rename Application

### ISSUE THREAD

**Issue by smnpaorg** [jmlopez-rod/ApplicationMaker#6]
How might I duplicate and rename a Application?

I believe this is an issue because it makes editing and forking simple applications incredibly difficult.

**Comment by akater** [comment]
Could you please give an example why you'd like to duplicate and rename a package? How would you use two copies? I can think of switching between PackageX` and PackageXDuplicate` in the `Needs` (or `BeginPackage`) expression for another package, in the same Application, or maybe using one copy for experiments in FrontEnd, and another one for commits.

Also, what's your editing evironment of choice? FrontEnd? Workbench? Something else?

…Sorry, It's only now that I notice: your issue is titled “Duplicate and Rename Application” but you're talking about duplicating and renaming packages. Just in case: Mathematica definitions are organised into Packages which are themselves organised into Applications, and distinguishing between them is quite important, especially in a repository like this one. :-)

**Comment by smnpaorg** [comment]
@akater I apologize I didn't even notice the error.  

It would be helpful for me.  Coping and pasting a package in a directory.  Like you said I don't really enjoy using github for managing system versions.

I'm purely working in the FrontEnd`

**Comment by akater** [comment]
Could you please restate this issue? Maybe we can close it?

(I still don't know whether you were tryng to duplicate a package or an application, and why.)

**Comment by smnpaorg** [comment]
This relates to and somewhat solves the issue http://mathematica.stackexchange.com/questions/57265/can-a-mathematica-application-be-inside-another-application/63171#63171

It can be closed.  If anyone can think of a way to fix the issue then I will file for a reopen.

**Comment by akater** [comment]
A good reference, thanks. I was interested if deeper contexts get loaded in agreement with Applications structure.

I guess you ended up with something like `$ApplicationsDirectory/InDevelopment/MyApplication`, or `$ApplicationsDirectory/MyApplication/CustomBranch`? Hopefully, I'll add both features one day, but not before I get a proper understanding of the rest of `ApplicationMaker`.
